# Generated by Django 4.0.4 on 2022-05-11 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackboneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='backbone model name')),
            ],
        ),
        migrations.CreateModel(
            name='SegModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='segmentation model name')),
                ('backbone_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deep_models.backbonemodel')),
            ],
        ),
    ]
