# Generated by Django 4.0.4 on 2022-05-11 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deep_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='the saved mode')),
            ],
        ),
        migrations.CreateModel(
            name='TrainAndTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('val', 'val'), ('test', 'test'), ('train', 'train')], max_length=5)),
                ('dataset', models.FilePathField()),
                ('save_freq', models.IntegerField()),
                ('epoch', models.IntegerField()),
                ('le', models.FloatField()),
                ('load_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deep_models.savedmodel')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deep_models.segmodel')),
            ],
        ),
    ]
