# Generated by Django 4.0.4 on 2022-05-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deep_models', '0002_savedmodel_trainandtest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainandtest',
            old_name='le',
            new_name='lr',
        ),
    ]
