# Generated by Django 4.0.4 on 2022-05-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_models', '0004_alter_trainandtest_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainandtest',
            name='prefix',
            field=models.CharField(default='a', max_length=10),
        ),
    ]
