# Generated by Django 4.0.4 on 2022-05-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_models', '0005_trainandtest_prefix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainandtest',
            old_name='load_model',
            new_name='load_name',
        ),
        migrations.RenameField(
            model_name='trainandtest',
            old_name='model',
            new_name='model_name',
        ),
        migrations.AlterField(
            model_name='trainandtest',
            name='prefix',
            field=models.CharField(default='a', help_text='default a', max_length=10),
        ),
    ]
