# Generated by Django 4.0.4 on 2022-05-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_models', '0007_mytest'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainandtest',
            name='backbone',
            field=models.CharField(default='', max_length=19),
        ),
    ]
