# Generated by Django 4.0.4 on 2022-05-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.FileField(default='txt/default.jpg', upload_to='txt/')),
            ],
        ),
    ]
